export const TABLES = {
  users: 'users',
  userTokens: 'user_tokens',
  products: 'products',
  prices: 'prices',
  allowed_sites: 'allowed_sites',
  visitors: 'unique_visitors',
  impressions: 'impressions',
  sitesPlans: 'sites_plans',
  sitePermissions: 'sites_permissions',
  problemReports: 'problem_reports',
  widgetSettings: 'widget_settings',
  newsletterSubscribers: 'newsletter_subscribers',
  userPlanTokens: 'user_plan_tokens',
  accessibilityReports: 'accessibility_reports',
  failedLoginAttempts: 'failed_login_attempts',
  cancelFeedback: 'cancel_feedback',
  organizations: 'organizations',
  organization_users: 'organization_users',
  workspaces: 'workspaces',
  workspace_users: 'workspace_users',
  workspace_invitations: 'workspace_invitations',
}

export const DEFAULT_LIMIT = 25
