import {
  ORGANIZATION_USER_ROLE_OWNER,
  ORGANIZATION_USER_ROLE_ADMIN,
} from './database.constant';

export const ORGANIZATION_MANAGEMENT_ROLES = [
  ORGANIZATION_USER_ROLE_OWNER,
  ORGANIZATION_USER_ROLE_ADMIN
] as const;
