export const WORKSPACE_USER_ROLE_OWNER = 'owner'
export const WORKSPACE_USER_ROLE_MEMBER = 'member'
export const WORKSPACE_USER_ROLE_ADMIN = 'admin'

export const WORKSPACE_USER_STATUS_ACTIVE = 'active'
export const WORKSPACE_USER_STATUS_PENDING = 'pending'
export const WORKSPACE_USER_STATUS_INACTIVE = 'inactive'
export const WORKSPACE_USER_STATUS_DECLINE = 'decline'

export const WORKSPACE_INVITATION_STATUS_PENDING = 'pending'
export const WORKSPACE_INVITATION_STATUS_ACCEPTED = 'accepted'
export const WORKSPACE_INVITATION_STATUS_DECLINED = 'declined'
export const WORKSPACE_INVITATION_STATUS_EXPIRED = 'expired'

export const WORKSPACE_MANAGEMENT_ROLES = [WORKSPACE_USER_ROLE_OWNER, WORKSPACE_USER_ROLE_ADMIN] as const

export type WorkspaceUserRole = typeof WORKSPACE_USER_ROLE_OWNER | typeof WORKSPACE_USER_ROLE_ADMIN | typeof WORKSPACE_USER_ROLE_MEMBER

export type WorkspaceUserStatus = typeof WORKSPACE_USER_STATUS_ACTIVE | typeof WORKSPACE_USER_STATUS_PENDING | typeof WORKSPACE_USER_STATUS_INACTIVE | typeof WORKSPACE_USER_STATUS_DECLINE

export type WorkspaceInvitationStatus = typeof WORKSPACE_INVITATION_STATUS_PENDING | typeof WORKSPACE_INVITATION_STATUS_ACCEPTED | typeof WORKSPACE_INVITATION_STATUS_DECLINED | typeof WORKSPACE_INVITATION_STATUS_EXPIRED
